### PR TITLE
Movie Support

### PR DESCRIPTION
**Pull request by SpeakingOfBrad**
I duplicated then reworked a lot of the tv show code so that it worked for movies too.
I also added "random" command for when you just can't choose what to watch.
Added pause/play commands when the remote isn't handy.
Added cancel for onDeck for when none of it sounds very interesting.
Added the ability to resume onDeck media from where you left off.

This fixes most of the current issues/feature requests.

### CODE REVIEW

**Comment by lanky8804** [comment]
Love my Plex and this is superb. Well done for the hard work :)

**Comment by lanky8804** [comment]
Just got my SiriProxy up and running, this is probably a stupid question but how do i add your movie support etc???

ATM i have just copied the normal text into my config file.

**Comment by SpeakingOfBrad** [comment]
Change the line that says
git: 'git://github.com/hjaltij/SiriProxy-Plex.git'
to
git: 'git://github.com/whoismezero/SiriProxy-Plex.git'

**Comment by lanky8804** [comment]
Excellent, thank you that got it working.

Couple of ideas dont know how feasible they are.  On my mac Plex has to be open for the commands to work, is it possible to add a command such as 'open plex' and it will open the app? also maybe a 'quit plex' to close the app?

**Comment by SpeakingOfBrad** [comment]
That can't be done with this plugin, but you can try bikr's siriproxy-launcher.

https://github.com/bikr/siriproxy-launcher

**Pull request merged**
